version: "3.9"

services:
  cuda-ssh:
    build:
      context: .
      dockerfile: Dockerfile
    image: torch-cu128-image:latest
    container_name: torch-cu128-container
    ports:
      - "2152:22"                   # SSH
      - "2151:21"                   # FTP
      - "21000-21010:21000-21010"   # FTP Passive ports
    runtime: nvidia
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4'
    #       memory: 4g
    environment:
      - USERS=${USERS}              # Defined in .env 
    volumes:
      - /mnt/d/containers/ubuntu/home:/home
    restart: unless-stopped
